### ISSUE TITLE
Failed to open /content/drive/MyDrive/SD/models/Lora/: No such file or directory. Aborting!

### ISSUE THREAD

**Issue by lloydsun** [AI-skimos/3line-colab-sd#5]
初次运行安装过程出错，提示没有相应文件夹。
出问题时drive 空间还剩 30 g

删除SD文件夹，再次运行，还是同样的错误。

`Failed to open /content/drive/MyDrive/SD/models/Lora/: No such file or directory. Aborting!

HEAD is now at a9fed7c3 Merge pull request #8503 from mcmonkey4eva/filename-length-limit-fix
HEAD is now at 47b6b60 Merge pull request #39 from CookieLau/patch-1
Python 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Traceback (most recent call last):
  File "/content/drive/MyDrive/SD/launch.py", line 380, in <module>
    prepare_environment()
  File "/content/drive/MyDrive/SD/launch.py", line 287, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "/content/drive/MyDrive/SD/launch.py", line 137, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "/content/drive/MyDrive/SD/launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "/usr/bin/python3" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check`

**Comment by AI-skimos** [comment]
你需要切换colab运行时，需要GPU加速才能跑的起来。

**Comment by lloydsun** [comment]
谢谢解答，改了后就可以了 ！
